//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitizenPortal.Resources.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Configuration() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitizenPortal.Resources.Views.Admin._Configuration", typeof(_Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: http://ogdifrance.cloudapp.net.
        /// </summary>
        public static string DataBrowserTooltip {
            get {
                return ResourceManager.GetString("DataBrowserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data explorer URL (DataBrowser).
        /// </summary>
        public static string DataBrowserUrl {
            get {
                return ResourceManager.GetString("DataBrowserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: http://ogdifrance.cloudapp.net:8080/v1.
        /// </summary>
        public static string DataServiceTooltip {
            get {
                return ResourceManager.GetString("DataServiceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data service URL (DataService).
        /// </summary>
        public static string DataServiceUrl {
            get {
                return ResourceManager.GetString("DataServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data sources.
        /// </summary>
        public static string DataSources {
            get {
                return ResourceManager.GetString("DataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recaptcha.
        /// </summary>
        public static string Recaptcha {
            get {
                return ResourceManager.GetString("Recaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For more information about this configuration, follow this &lt;a href=&quot;http://www.google.com/recaptcha&quot; target=&quot;_blank&quot;&gt;link&lt;/a&gt;..
        /// </summary>
        public static string RecaptchaHint {
            get {
                return ResourceManager.GetString("RecaptchaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Private key.
        /// </summary>
        public static string RecaptchaPrivateKey {
            get {
                return ResourceManager.GetString("RecaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public key.
        /// </summary>
        public static string RecaptchaPublicKey {
            get {
                return ResourceManager.GetString("RecaptchaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à News feed address.
        /// </summary>
        public static string RssAddress {
            get {
                return ResourceManager.GetString("RssAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: http://rss.lemonde.fr/c/205/f/3050/index.rss.
        /// </summary>
        public static string RssAddressTooltip {
            get {
                return ResourceManager.GetString("RssAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RSS feed.
        /// </summary>
        public static string RssFeed {
            get {
                return ResourceManager.GetString("RssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitter feed address.
        /// </summary>
        public static string TwitterAddress {
            get {
                return ResourceManager.GetString("TwitterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=opendatabdx.
        /// </summary>
        public static string TwitterAddressTooltip {
            get {
                return ResourceManager.GetString("TwitterAddressTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitter feed.
        /// </summary>
        public static string TwitterFeed {
            get {
                return ResourceManager.GetString("TwitterFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For more information about this configuration, follow this &lt;a href=&quot;https://dev.twitter.com/docs&quot; target=&quot;_blank&quot;&gt;link&lt;/a&gt;..
        /// </summary>
        public static string TwitterHint {
            get {
                return ResourceManager.GetString("TwitterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bearer token.
        /// </summary>
        public static string TwitterToken {
            get {
                return ResourceManager.GetString("TwitterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example: AAAAAAAAAAAAAAAAAAAAAP0aRAAAAAAA74FNFEMqC2Z4GszhdVJbh8uJFPE%3DA3Wd0AxtkbFD6mk6TDhtsVYRgmrkHONxnbH4lwH1DY.
        /// </summary>
        public static string TwitterTokenTooltip {
            get {
                return ResourceManager.GetString("TwitterTokenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account key.
        /// </summary>
        public static string WindowsAzureAccountKey {
            get {
                return ResourceManager.GetString("WindowsAzureAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account name.
        /// </summary>
        public static string WindowsAzureAccountName {
            get {
                return ResourceManager.GetString("WindowsAzureAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Azure storage account.
        /// </summary>
        public static string WindowsAzureStorage {
            get {
                return ResourceManager.GetString("WindowsAzureStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your must use your OGDI DataLab configuration account..
        /// </summary>
        public static string WindowsAzureStorageHint {
            get {
                return ResourceManager.GetString("WindowsAzureStorageHint", resourceCulture);
            }
        }
    }
}
