//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitizenPortal.Resources.Views.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Show {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Show() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitizenPortal.Resources.Views.Data.Show", typeof(Show).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or unselect column to display in the table.
        /// </summary>
        public static string ColumnDisplayed {
            get {
                return ResourceManager.GetString("ColumnDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data extract.
        /// </summary>
        public static string DataExtract {
            get {
                return ResourceManager.GetString("DataExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset not found..
        /// </summary>
        public static string DatasetNotFound {
            get {
                return ResourceManager.GetString("DatasetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartographic visualization.
        /// </summary>
        public static string DataVisualization {
            get {
                return ResourceManager.GetString("DataVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in Atom format.
        /// </summary>
        public static string DownloadAtomTitle {
            get {
                return ResourceManager.GetString("DownloadAtomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in CSV format.
        /// </summary>
        public static string DownloadCSVTitle {
            get {
                return ResourceManager.GetString("DownloadCSVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in Daisy format.
        /// </summary>
        public static string DownloadDaisyTitle {
            get {
                return ResourceManager.GetString("DownloadDaisyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in JSON format.
        /// </summary>
        public static string DownloadJSONTitle {
            get {
                return ResourceManager.GetString("DownloadJSONTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in KML format.
        /// </summary>
        public static string DownloadKMLTitle {
            get {
                return ResourceManager.GetString("DownloadKMLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download data in RDF format.
        /// </summary>
        public static string DownloadRDFTitle {
            get {
                return ResourceManager.GetString("DownloadRDFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General description.
        /// </summary>
        public static string GeneralDescription {
            get {
                return ResourceManager.GetString("GeneralDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string GeneralDescriptionCatalog {
            get {
                return ResourceManager.GetString("GeneralDescriptionCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string GeneralDescriptionCategory {
            get {
                return ResourceManager.GetString("GeneralDescriptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GeneralDescriptionDescription {
            get {
                return ResourceManager.GetString("GeneralDescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic area.
        /// </summary>
        public static string GeneralDescriptionGeozone {
            get {
                return ResourceManager.GetString("GeneralDescriptionGeozone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string GeneralDescriptionLicense {
            get {
                return ResourceManager.GetString("GeneralDescriptionLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open license.
        /// </summary>
        public static string GeneralDescriptionOpenLicense {
            get {
                return ResourceManager.GetString("GeneralDescriptionOpenLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string GeneralDescriptionRating {
            get {
                return ResourceManager.GetString("GeneralDescriptionRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel my vote.
        /// </summary>
        public static string RateCancel {
            get {
                return ResourceManager.GetString("RateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative vote.
        /// </summary>
        public static string RateNegative {
            get {
                return ResourceManager.GetString("RateNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive vote.
        /// </summary>
        public static string RatePositive {
            get {
                return ResourceManager.GetString("RatePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical description.
        /// </summary>
        public static string TechnicalDescription {
            get {
                return ResourceManager.GetString("TechnicalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        public static string TechnicalDescriptionPublicationDate {
            get {
                return ResourceManager.GetString("TechnicalDescriptionPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last release date.
        /// </summary>
        public static string TechnicalDescriptionReleaseDate {
            get {
                return ResourceManager.GetString("TechnicalDescriptionReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string TechnicalDescriptionResourceType {
            get {
                return ResourceManager.GetString("TechnicalDescriptionResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string TechnicalDescriptionSource {
            get {
                return ResourceManager.GetString("TechnicalDescriptionSource", resourceCulture);
            }
        }
    }
}
