//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18033
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitizenPortal.Resources.Views.Data {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Show {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Show() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CitizenPortal.Resources.Views.Data.Show", typeof(Show).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data extract.
        /// </summary>
        public static string DataExtract {
            get {
                return ResourceManager.GetString("DataExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dataset not found..
        /// </summary>
        public static string DatasetNotFound {
            get {
                return ResourceManager.GetString("DatasetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cartographic visualization.
        /// </summary>
        public static string DataVisualization {
            get {
                return ResourceManager.GetString("DataVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download data in Atom format.
        /// </summary>
        public static string DownloadAtomTitle {
            get {
                return ResourceManager.GetString("DownloadAtomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download data in CSV format.
        /// </summary>
        public static string DownloadCSVTitle {
            get {
                return ResourceManager.GetString("DownloadCSVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download data in Daisy format.
        /// </summary>
        public static string DownloadDaisyTitle {
            get {
                return ResourceManager.GetString("DownloadDaisyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download data in JSON format.
        /// </summary>
        public static string DownloadJSONTitle {
            get {
                return ResourceManager.GetString("DownloadJSONTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download data in KML format.
        /// </summary>
        public static string DownloadKMLTitle {
            get {
                return ResourceManager.GetString("DownloadKMLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General description.
        /// </summary>
        public static string GeneralDescription {
            get {
                return ResourceManager.GetString("GeneralDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catalog.
        /// </summary>
        public static string GeneralDescriptionCatalog {
            get {
                return ResourceManager.GetString("GeneralDescriptionCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        public static string GeneralDescriptionCategory {
            get {
                return ResourceManager.GetString("GeneralDescriptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string GeneralDescriptionDescription {
            get {
                return ResourceManager.GetString("GeneralDescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geographic area.
        /// </summary>
        public static string GeneralDescriptionGeozone {
            get {
                return ResourceManager.GetString("GeneralDescriptionGeozone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à License.
        /// </summary>
        public static string GeneralDescriptionLicense {
            get {
                return ResourceManager.GetString("GeneralDescriptionLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open license.
        /// </summary>
        public static string GeneralDescriptionOpenLicense {
            get {
                return ResourceManager.GetString("GeneralDescriptionOpenLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rating.
        /// </summary>
        public static string GeneralDescriptionRating {
            get {
                return ResourceManager.GetString("GeneralDescriptionRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel my vote.
        /// </summary>
        public static string RateCancel {
            get {
                return ResourceManager.GetString("RateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Negative vote.
        /// </summary>
        public static string RateNegative {
            get {
                return ResourceManager.GetString("RateNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positive vote.
        /// </summary>
        public static string RatePositive {
            get {
                return ResourceManager.GetString("RatePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical description.
        /// </summary>
        public static string TechnicalDescription {
            get {
                return ResourceManager.GetString("TechnicalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publication date.
        /// </summary>
        public static string TechnicalDescriptionPublicationDate {
            get {
                return ResourceManager.GetString("TechnicalDescriptionPublicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last release date.
        /// </summary>
        public static string TechnicalDescriptionReleaseDate {
            get {
                return ResourceManager.GetString("TechnicalDescriptionReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resource type.
        /// </summary>
        public static string TechnicalDescriptionResourceType {
            get {
                return ResourceManager.GetString("TechnicalDescriptionResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string TechnicalDescriptionSource {
            get {
                return ResourceManager.GetString("TechnicalDescriptionSource", resourceCulture);
            }
        }
    }
}
